### ISSUE TITLE
Error - Must not define both SQLITE_OMIT_DECLTYPE and SQLITE_ENABLE_COLUMN_METADATA

### ISSUE THREAD

**Issue by Pranav-Suresh** [brody2consult/cordova-sqlite-storage#906] opened 2020-01-14 10:43 UTC
I have a forcehybrid + ionic 1 app which uses cordova-sqlite-storage plugin. I am getting build error while trying to build it via XCode.
`Must not define both SQLITE_OMIT_DECLTYPE and SQLITE_ENABLE_COLUMN_METADATA"`

Xcode version - 11.3
Build Target - iOS 12.2

**Comment by brody2consult** [comment] 2020-01-14 11:06
This seems to be a customization. I guess you would have to remove `SQLITE_OMIT_DECLTYPE` if you define `SQLITE_ENABLE_COLUMN_METADATA`.

**Comment by Pranav-Suresh** [comment] 2020-01-14 13:00
<img width="724" alt="Screenshot 2020-01-14 at 6 35 20 PM" src="https://user-images.githubusercontent.com/26004418/72347237-ac167480-36fd-11ea-808a-eb4990bc1bfc.png">
I am using this plugin in a hybrid application using cordova + ionic + salesforce. I did not customise the plugin. It throws this error while trying to build the application using xcode.

cordova-ios - 5.0.0
cordova - 8.1.2

**Comment by brody2consult** [comment] 2020-01-14 13:38
This looks like some kind of an issue with your build. Please do the following:

- do `cordova plugin ls` and `cordova platform ls`
- completely remove `plugins` and `platforms` from your workarea (they should normally not be committed)
- ensure that you are using the latest version of this plugin (I generally do not support old releases unless absolutely necessary)
- ensure that you do not have multiple SQLite plugins
- ensure that your plugins are configured in `package.json` and not `config.xml` (Cordova should do this migration for you but I have seen some problems with it in the past)

In general I would recommend doing `cordova plugin add` to add the recent versions of all required plugins to package.json.

In case this issue persists for you I would really need a demo project to understand what may be going on.

**Comment by Pranav-Suresh** [comment] 2020-01-16 07:01
I have tried the solution you gave, but nothing worked.

I have created a sample app where you can check.
https://drive.google.com/open?id=1YnVK9nJ0zK6bF3cc17Wo121jDQkNSrD8

**Comment by brody2consult** [comment] 2020-01-16 20:50
I tried downloading your sample app, opening the project on Xcode, and building but it failed due to some kind of an issue with a plist file.

I then tried the following:

- `rm -rf _npmignore _DS_Store`
- `rm -rf package-lock.json plugins platforms`
- `cordova platform add ios`
- `open platforms/ios/HelloCordova.xcodeproj` to open it with Xcode
- build and run on Simulator

I was able to build and run, just get a page that said "Contacts". I saw this message in the console window: `ERROR: Salesforce Mobile SDK OAuth plugin not available`

At this point I would still say that there is something really wrong with your own project, not with this plugin.

I would highly recommend that you start with a blank Cordova project or Ionic starter project and try adding one thing at a time until you can see what does and does not work correctly.

In case you do want to demonstrate an issue with this plugin, please make a project on GitHub with a [minimal, reproducible example ([1])](https://stackoverflow.com/help/minimal-reproducible-example), with no `plugins` or `platforms` directories.

[1] https://stackoverflow.com/help/minimal-reproducible-example

**Closed as completed** 2020-02-06 18:32 UTC
Labels: invalid

**Comment by AubreyHewes** [comment] 2020-06-06 05:21
@Pranav-Suresh When I ran in to your described problem it mainly means that you have also added the `cordova-sqlite-storage` to a salesforce-hybrid cordova app (which has its own `sqlite3.c` `sqlite3.h` via pod [`SQLCipher`](https://github.com/forcedotcom/SalesforceMobileSDK-CordovaPlugin/blob/c1570b4cb1796e75e6befb5022574a84525b74c4/plugin.xml#L110)).

In xcode-ui just dereference the `sqlite3.c` and `sqlite3.h` from the `Plugins` directory.. then it should be able to compile..

To test/reproduce create a new ios project using the [forcehybrid](https://www.npmjs.com/package/forcehybrid) command.. can compile no probs..  then add `cordova-sqlite-storage`.. oh no.. broken compile. and then in xcode-ui do as described.. yay!

@brodybits the salesforce sdk cordova plugin requires pod [`SQLCipher`](https://github.com/forcedotcom/SalesforceMobileSDK-CordovaPlugin/blob/c1570b4cb1796e75e6befb5022574a84525b74c4/plugin.xml#L110) which also has `sqlite3.c` `sqlite3.h`..so breaks the build as described when adding this plugin. Removing the `sqlite3.c` `sqlite3.h` from the `Plugins` dir in xcode-ui (so the files added by this plugin `cordova-sqlite-storage`).. fixes the build problem. Though any problems thereafter are not your problem (as is not your dist of sqlite) 

Anyway my 2cts x

**Comment by Pranav-Suresh** [comment] 2020-06-08 06:18
@AubreyHewes You are right!. This is how I was able to overcome this issue.
