### ISSUE TITLE
Why db.transaction not working and show nothing in while block ?

### ISSUE THREAD

**Issue by BilelKrichen** [brody2consult/cordova-sqlite-storage#349] opened 2015-09-17 13:19 UTC
I would like to raise a question if possible. 
The alert("test") not working also the tx.executeSql and 
 the console show this issue : <b>new transaction is waiting for open operation at file:///android_asset/www/plugins/io.litehelpers.cordova.sqlite/www/SQLitePlugin.js:105</b>

``` javascript
document.addEventListener("deviceready", onDeviceReady, false);
var bool=true;

function onDeviceReady() 

{
     db = window.sqlitePlugin.openDatabase({name: "MyDB.db"});
    while(bool==true)
    {
         db.transaction(FunctionTorepeat, errorCB , successCB );
    }
}   
    function errorCB(err) 
    {
        alert("Error processing SQL: "+err);
    }
    function successCB() {
        alert("success!!");    
    }
    function FunctionTorepeat(tx)
    {
            alert("Test");
            tx.executeSql("select * from table" , [] , querysuccess,errorCB);
    } 
```

Thanks

**Comment by 0xae** [comment] 2015-09-18 18:46
+1, have the same behaviour here !

**Comment by brody2consult** [comment] 2015-09-20 10:20
Guys this is not enough information. Please describe which platform you see this issue in. Also the `Functiontorepeat()` references `querysuccess` which is not included here.

**Comment by ncandido** [comment] 2015-10-02 09:57
I have the sane problem db.transaction block without reason (by a seconds) and only after execute the query. 

This problem its raddon not a constant problema but affect my app 

Works fine on iOS 8 and Android, but not in iOS 9!

**Comment by brody2consult** [comment] 2015-10-19 11:01
Closing due to lack of reproduction scenario. According to the support policies stated in README.md free support is only offered when a minimum complete, self-contained test program can be provided.

**Closed as completed by brody2consult** 2015-10-19 11:01 UTC
Labels: invalid, question, info needed

**Comment by chitrajs** [comment] 2018-02-02 13:45
myDB.transaction(function (transaction) {
            transaction.executeSql('CREATE TABLE IF NOT EXISTS codesundar (id integer primary key, title text, desc text)', [],
            function (tx, result) {
                alert("Table created successfully");
            },
            function (error) {
                alert("Error occurred while creating the table.");
            });
        });

it's not working on windows Phone, can any one suggest on this.

**Comment by brody2consult** [comment] 2018-03-05 17:16
@chitrajs please request help on cordova-sqlite-help with complete test program to reproduce, also this plugin version does NOT support wp8 platform any more.
