### ISSUE TITLE
Cordova x64 embedded and sqlite fails to start

### ISSUE THREAD

**Issue by danielehrhardt** [brody2consult/cordova-sqlite-storage#752] opened 2018-02-09 18:12 UTC
Hi guys,

I have the following problem when I start a new Cordova project and add crosswalk with the following parameters:
```
"cordova-plugin-crosswalk-webview": {
                "XWALK_MULTIPLEAPK": "false",
                "XWALK_VERSION": "23+",
                "XWALK_LITEVERSION": "xwalk_core_library_canary:17+",
                "XWALK_COMMANDLINE": "--disable-pull-to-refresh-effect",
                "XWALK_MODE": "embedded"
            },
```
and add the sqlite plugin and try to start the app on a x64 cpu device i get the following Message:
![image](https://user-images.githubusercontent.com/19570043/36042723-1dacd848-0dcd-11e8-9f34-2ed868266a78.png)

i hope someone can help

could be related to https://github.com/litehelpers/Cordova-sqlite-storage/issues/336

https://github.com/danielehrhardt/sqlite-cordova-error

**Comment by brody2consult** [comment] 2018-02-11 13:45
Closing as duplicate of #336. Please see <https://github.com/litehelpers/Cordova-sqlite-storage/issues/336#issuecomment-364752652> for workaround solution.

**Closed as completed by brody2consult** 2018-02-11 13:45 UTC
Labels: duplicate, question
