### ISSUE TITLE
Cannot read property 'openDatabase' of undefined

### ISSUE THREAD

**Issue by ghost** [brody2consult/cordova-sqlite-storage#911] opened 2020-01-27 19:21 UTC
I am trying to sort out the error but when I run 

in android it shows
Uncaught TypeError: Cannot read property 'openDatabase' of undefined
    at Channel.<anonymous> (index.js:4)
    at Channel.fire (cordova.js:846)
    at cordova.js:231

in browser
OPEN database: my.db
cordova.js:1001 Error: exec proxy not found for :: SQLitePlugin :: close
cordova.js:1001 Error: exec proxy not found for :: SQLitePlugin :: open
SQLitePlugin.js:196 OPEN database: my.db FAILED, aborting any pending transactions
SQLitePlugin.js:82 Could not open database

index.html
<html>
    <head>

        <meta http-equiv="Content-Security-Policy" content="default-src 'self' data: gap: https://ssl.gstatic.com 'unsafe-eval'; style-src 'self' 'unsafe-inline'; media-src *; img-src 'self' data: content:;">
        <meta name="format-detection" content="telephone=no">
        <meta name="msapplication-tap-highlight" content="no">
        <meta name="viewport" content="initial-scale=1, width=device-width, viewport-fit=cover">
        <link rel="stylesheet" type="text/css" href="css/index.css">
        <title>Hello World</title>
    </head>
    <body>
        <div class="app">
            <h1>Apache Cordova</h1>
            <div id="deviceready" class="blink">
              
            </div>
        </div>
        <script type="text/javascript" src="cordova.js"></script>
        <script type="text/javascript" src="js/index.js"></script>
    </body>
</html>

index.js
var db = null;

document.addEventListener('deviceready', function() {
  db = window.sqlitePlugin.openDatabase({
    name: 'my.db',
    location: 'default',
  });
});

please helppp

**Comment by brody2consult** [comment] 2020-01-27 19:24
This looks like an issue with the installation of this plugin. Please double-check your installation very carefully. You may want to consider trying out the starter that I documented in README.md.

**Comment by ghost** [comment] 2020-01-27 19:29
I have followed bellow instruction, exact same

Quick installation
Use the following command to install this plugin version from the Cordova CLI:
cordova create sqlIte
cordova plugin add cordova-sqlite-storage
cordova platform add android

**Comment by brody2consult** [comment] 2020-01-27 19:33
Please post a minimal reproduction app on GitHub, with no `plugins` or `platforms` committed. See this: https://stackoverflow.com/help/minimal-reproducible-example

**Comment by nehalasim** [comment] 2020-01-27 19:39
is it require any jquery file??

**Comment by ghost** [comment] 2020-01-27 19:40
is it require any jquery file??
and is it require to reconfigure the config.xml file??

**Comment by brody2consult** [comment] 2020-01-27 19:43
Please try the following:

- completely remove all plugin and platform configurations from config.xml
- ensure you have package.json but with no plugins or platforms configured
- add this plugin and desired platform using the Cordova CLI

Then you should not see this issue any longer.

Cordova switched from using config.xml to using package.json to configure the plugins and platforms. It has some automatic migration but I have seen it go wrong and would recommend a cleaner solution like I recommended above.

**Comment by ghost** [comment] 2020-01-27 19:57
it showing the same error. 
Is it require to add plugin in config.xml. if it is then what is the version and spec

**Comment by ghost** [comment] 2020-01-27 20:08
Again I created the new app added plugin, added platform but showing same issue

**Comment by brody2consult** [comment] 2020-01-27 20:09
I would really need to see a reproduction project on GitHub to help further with your issue.

**Comment by brody2consult** [comment] 2020-01-27 20:11
Private commercial support is also available. Please contact <sales@xpbrew.consulting> for more information in case you are interested.

**Comment by ghost** [comment] 2020-01-27 20:16
https://github.com/nehalasim/sql

please check is it enough to check

**Comment by brody2consult** [comment] 2020-01-27 20:26
It looks to me like you tried to run on the browser platform, which is not supported by this plugin. From a quick look I think it should work on Android without any problems.

It also seems to me like you put all the artifacts in a flat structure. I would really need everything in the right subfolders if you need me to reproduce your issue. Also no platform JSON files such as browser.json or android.json.

I am also finishing pretty soon for today, can look later tonight or tomorrow if needed.

And please do accept my apologies for not thinking of the problem on the browser platform.

**Comment by ghost** [comment] 2020-01-27 20:28
[sqliteNew (2).zip](https://github.com/xpbrew/cordova-sqlite-storage/files/4119190/sqliteNew.2.zip)

**Comment by ghost** [comment] 2020-01-27 20:30
I have added this zip {sqliteNew (2).zip} file with all files and folder. if yiu are closing now, please help me when you will be back tomorrow,
i understand its not for browser. here i have added both platforms error, for your better understaning.
the error is
in android it shows
Uncaught TypeError: Cannot read property 'openDatabase' of undefined
at Channel. (index.js:4)
at Channel.fire (cordova.js:846)
at cordova.js:231

in browser
OPEN database: my.db
cordova.js:1001 Error: exec proxy not found for :: SQLitePlugin :: close
cordova.js:1001 Error: exec proxy not found for :: SQLitePlugin :: open
SQLitePlugin.js:196 OPEN database: my.db FAILED, aborting any pending transactions
SQLitePlugin.js:82 Could not open database

**Comment by ghost** [comment] 2020-01-28 15:46
did you get the time to check sqliteNew (2).zip project?
Please I really need your help

**Comment by brody2consult** [comment] 2020-01-28 16:03
I just tried running your project on Android, on my Android emulator, seems to work OK. Here is some logs from logcat:

```
D/SystemWebChromeClient( 7928): file:///android_asset/www/plugins/cordova-sqlite-storage/www/SQLitePlugin.js: Line 175 : OPEN database: my.db
I/chromium( 7928): [INFO:CONSOLE(175)] "OPEN database: my.db", source: file:///android_asset/www/plugins/cordova-sqlite-storage/www/SQLitePlugin.js (175)
V/SQLitePlugin( 7928): Android db implementation: built-in android.database.sqlite package
E/eglCodecCommon( 7928): glUtilsParamSize: unknow param 0x000085b5
V/info    ( 7928): Open sqlite db: /data/data/io.cordova.hellocordova/databases/my.db
D/CordovaWebViewImpl( 7928): onPageFinished(file:///android_asset/www/index.html)
D/SystemWebChromeClient( 7928): file:///android_asset/www/plugins/cordova-sqlite-storage/www/SQLitePlugin.js: Line 179 : OPEN database: my.db - OK
I/chromium( 7928): [INFO:CONSOLE(179)] "OPEN database: my.db - OK", source: file:///android_asset/www/plugins/cordova-sqlite-storage/www/SQLitePlugin.js (179)
D/SystemWebChromeClient( 7928): file:///android_asset/www/plugins/cordova-sqlite-storage/www/SQLitePlugin.js: Line 80 : DB opened: my.db
I/chromium( 7928): [INFO:CONSOLE(80)] "DB opened: my.db", source: file:///android_asset/www/plugins/cordova-sqlite-storage/www/SQLitePlugin.js (80)
```

It looks to me like you tried to run on the browser platform. As I tried to explain before, that will not work since this plugin does not directly support running on the browser platform.

**Closed as completed** 2020-02-01 15:35 UTC
Labels: invalid
