### ISSUE TITLE
SQLite DB not accessible in iOS

### ISSUE THREAD

**Issue by vageesans** [brody2consult/cordova-sqlite-storage#789] opened 2018-05-28 17:14 UTC
Hi

I had an existing app with sqlite db, we updated ionic and Cordova, removed and added platform iOS (4.5.4). Its an ionic v1 sidemenu app. 

It works as expected in Android and Web.

In iOS, The app builds successfully. 
But the DB Select statement is not getting executed.
It freezes.

**Comment by brody2consult** [comment] 2018-06-03 19:11
Please post the smallest demo possible that is complete and self-contained to demonstrate this issue. Major bonus if you can make the demo without Ionic, using <https://github.com/brodybits/cordova-sqlite-storage-starter-app> (testing with Ionic and Angular frameworks is very limited).

**Comment by Ilyoskhuja** [comment] 2018-06-19 11:18
I have same problem in my ionic app (sqlite: 4.7.0)

**Comment by Enoges** [comment] 2018-06-27 09:06
Same problem here.
How can I give you info that you need??

**Comment by brody2consult** [comment] 2018-06-29 14:56
To get help with Ionic I would recommend that you guys file an issue on Ionic Native, along with a project that can demonstrate the issue. Plugins should be specified in config.xml (recent versions of Cordova CLI will do this automatically), artifacts in plugins and platforms directories should not be included. Project on GitHub would be best, project ZIP on DropBox would be OK as well.

There are plenty of existing samples that should be working on all supported platforms. I would recommend a process of changing one thing at a time to determine what does and does not work on all platforms.

For priority, commercial support please contact <sales@litehelpers.net> for more information.

**Comment by Enoges** [comment] 2018-07-02 07:06
I search and i can't found an iOS correct sample.
Can you post some of that plenty of existing samples, pls?

**Comment by brody2consult** [comment] 2018-07-02 11:14
Recommended starting point for Ionic 3: <https://github.com/iursevla/ionic3-PreDB> (uses cordova-sqlite-ext plugin version)

Recommended starting point without Ionic: <https://github.com/brodybits/cordova-sqlite-storage-starter-app>

Closing for now due to lack of reproduction. In case anyone can demonstrate an issue with this plugin and post the demo I would be very happy to take a look.

**Closed as completed by brody2consult** 2018-07-02 11:14 UTC
Labels: question, doc-todo, info needed, user community help, doc-general, ionic

**Comment by brody2consult** [comment] 2018-07-02 11:35
P.S. I just discovered that the recommended starting point for Ionic 3 is missing in the documentation, will be part of upcoming major release ref: #773 

I would also like to see Ionic 4 starting point, just raised #796.
