### ISSUE TITLE
Plugin not work on iOS

### ISSUE THREAD

**Issue by olaferlandsen** [brody2consult/cordova-sqlite-storage#500] opened 2016-06-11 15:03 UTC
Well first of all, this example work fine on android but not on iOS, and my system information is:
- OS X El Capitan (10.11.5), 2,8 GHz Intel Core i7, 8GB Ram
- Cordova 6.2.0
- Crosswalk Webview Plugin 1.7.0
- Xcode 7.3.1

My code:
Structure:

```
www/
    js/
        app.js
        index.html.js
        profile.html.js
    css/
    index.html
    profile.html
```

app.js

``` javascript
var database;
document.addEventListener('deviceready', function(){
    database        =   window.sqlitePlugin.openDatabase({
        name: "database.db",
        androidDatabaseImplementation: 2,
        androidLockWorkaround: 1,
        location:'default'
    });
    database.executeSql('SELECT tbl_name FROM sqlite_master WHERE type = \'table\'', [], function (result) {
        if(result.rows.length == 0) {
            database.executeSql('CREATE TABLE IF NOT EXISTS Profiles (id INT PRIMARY KEY NOT NULL,name TEXT,createdAt DATETIME DEFAULT CURRENT_TIMESTAMP)');
        }
    });
});
```

index.html.js

``` javascript
document.addEventListener('deviceready', function(){
    database.executeSql('SELECT name FROM Profiles', [], function (result) {
        console.info('rows : ' + result.rows.length);
    }, function(error){
        console.error(error.message);
    });
});
```

index.html

``` html
<html>
    <head>
        <title>Index</title>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <meta name="description" content="Description" />
        <script src="js/jquery.min.js"></script>
        <script src="js/mustache.min.js"></script>
        <script src="cordova.js"></script>
    </head>
    <body>
        <p>Demo</p>
        <!-- ... -->

        <script src="js/app.js"></script>
        <script src="js/index.html.js"></script>
    </body>
</html>
```

This code dont show me error and logs, and i don't know whats happend.

So, i open debbug tool from Safari, and execute de next script(to test but nothing...):

``` javascript
database.executeSql('CREATE TABLE IF NOT EXISTS Demo (id INT);');

database.executeSql('SELECT name FROM sqlite_master', [], function (result) {
    console.info('rows : ' + result.rows.length);
}, function(error){
    console.error(error.message);
});
```

When i run app on my iPad with xCode. the debug tool say "Good News: SQLite is thread safe!"

**Comment by brody2consult** [comment] 2016-06-14 09:29
Did you try the echoTest and selfTest functions?

**Comment by olaferlandsen** [comment] 2016-06-14 12:20
i dont know whats is echoTest and selfTest, sorry

**Comment by olaferlandsen** [comment] 2016-06-14 12:20
i dont know whats is echoTest and selfTest, sorry

**Comment by olaferlandsen** [comment] 2016-06-14 12:21
i dont know whats is echoTest and selfTest, sorry

**Comment by brody2consult** [comment] 2016-06-14 12:28
The plugin API includes echoTest and selfTest functions. These are documented in README.md. You can use the echoTest function to verify that the plugin installation is OK. You can use the selfTest function to verify that the plugin can create a test database, add some data, read the data, and clean it up.

I added these test functions to the API to help pinpoint installation and setup problems. People have been using this plugin on Android and iOS for years so I find this kind of problem to be really strange.

**Comment by brody2consult** [comment] 2016-06-14 12:30
My apologies, I didn't mean to close it, reopening it (again). Please try these test functions and report the results then we have more information to help find the cause.

**Comment by brody2consult** [comment] 2016-07-29 15:08
@olaferlandsen can you confirm whether or not you got it working? I would like to close this unless you are still having problems.

**Comment by ShawnXu** [comment] 2016-08-15 02:04
I'm using an ionic wrapper http://ionicframework.com/docs/v2/native/sqlite/. On iOS, I always got a "no such table" error, it turns out that executeSql() has to be called after 
1. openDatabase()
2. a table creation statement 

Her is my implementation 

```
export class CacheService {

  // Mind the traps
  // 1. sql must excute AFTER database is open
  // 2. cache keys that are too long does NOT work

  storage: SQLite;

  constructor() {
    this.storage = new SQLite();
    this.open();
  }

  open() {
      return this.storage
        .openDatabase({
          name: 'alexanderst.db',
          location: 'default'
        })
        .then(
          rs => {
            return this.storage.executeSql(
              `CREATE TABLE IF NOT EXISTS cache (
                cache_key CHAR(255) UNIQUE,
                cache_value TEXT NOT NULL)`,
              []
            )
            .then(
              () => Log.debug('cache table created'),
              err => Log.error('table creation failed', err)
            );
          },
          err => console.log('failed to open database')
        );
  }

  get(key) {
    Log.debug('cache get', key);
    return new Promise<any>((resolve, reject) => {
      this.open()
        .then(
          rs => {
            this.storage.executeSql(
              `SELECT cache_value FROM cache WHERE cache_key = ?`,
              [key]
            )
            .then(
              rs => {
                Log.debug('cache hit', key, rs.rows.item(0));
                try {
                  let value = rs.rows.item(0).cache_value;
                  resolve(value);
                } catch (e) {
                  Log.error('cache error');
                  reject('cache error');
                }
              },
              err => {
                Log.debug('cache miss', key, err);
                reject(err);
              }
            );
          },
          err => reject(err)
        );
    });
  }

  set(key, value) {
    return this.open()
      .then(
        rs => {
          return this.storage.executeSql(
            `INSERT OR REPLACE INTO cache VALUES (?, ?)`,
            [key, value]
          )
          .then(
            rs => {
              if (rs.rowsAffected) {
                Log.debug('cache set', key);
              } else {
                Log.error('failed writing to cache', key);
              }
            },
            err => {
              Log.error('failed writing to cache', key, err);
            }
          );
        }
      );
  }
}

```

I don't know why it's like this but at least now it's working for me.

**Comment by brody2consult** [comment] 2016-08-19 12:51
Unfortunately I really cannot follow what are the actual problems discussed here. In general it should be possible to open a database, create a table, and add data if the table already exists. Yes there is definitely a significant number of quirks, pitfalls, and other gotchas but I have these are largely documented.

I have already spent a bit of time documenting the known quirks and pitfalls, adding test functions, adding sample code, publishing a test project, etc. The test functions are provided to verify that the plugin is properly installed and the code waits for the 'deviceready' event before attempting to open a database.

Using this plugin with Ionic and other Angular derivatives can be especially tricky. Some samples have been linked in the documentation. Again I think the known Angular-related quirks and pitfalls have been documented. In general I do not provide free support for use with Angular due to the amount of work it can take to find the cause of the issues encountered.

If you continue to encounter any more problems please describe them very clearly and post a minimal test project to demonstrate what is going on. Otherwise I will close this issue after the next couple weeks or so.

**Closed as completed** 2017-01-22 17:43 UTC
Labels: question, doc-todo, info needed
